# Generated by Django 4.1 on 2024-10-30 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_image_paragraph"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="summery",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
